- hosts: ec2_dev
  name: Copies terraform configs to remotes, plans and applies terraform
  vars:
    plan_only: yes
  become: true
  tasks:
    - name: Copy terraform dir to remotes
      copy:
        dest: ~/terraform/
        src: terraform/

    - name: Run Terraform Task
      check_mode: "{{ plan_only }}" # can pass via env yes | no
      register: terraform
      community.general.terraform:
        project_path: "~/terraform/"
        #backend_config:
        #  region: "eu-north-1"
        #  bucket: "mernxl--terraform-states"
        #  key: "ansible-terraform/{{ inventory_hostname }}.tfstate"
        state: present
        backend_config_files:
        force_init: true

    - name: View Output
      debug: var=terraform.stdout_lines
