- hosts: ec2_dev
  name: Copies terraform configs to remotes, plans and applies terraform
  become: true
  tasks:
    - name: Copy terraform dir to remotes
      copy:
        dest: ~/terraform/
        src: terraform/

    - name: Plan Task
      check_mode: yes # can pass via env
      register: plan
      community.general.terraform:
        project_path: "~/terraform/"
        #backend_config:
        #  region: "eu-north-1"
        #  bucket: "mernxl--terraform-states"
        #  key: "ansible-terraform/{{ inventory_hostname }}.tfstate"
        state: present
        backend_config_files:
        force_init: true

    - name: Preview the Plan
      debug: var=plan.stdout_lines

    - name: Apply Task
      register: apply
      community.general.terraform:
        project_path: "~/terraform/"
        #backend_config:
        #  region: "eu-north-1"
        #  bucket: "mernxl--terraform-states"
        #  key: "ansible-terraform/{{ inventory_hostname }}.tfstate"
        state: present
        force_init: true

    - name: Preview the Apply
      debug: var=apply.stdout_lines
