- hosts: all
  name: Copies terraform configs to remotes, plans and applies terraform
  vars:
    plan_only: yes
    state: present
    env: dev
  become: true
  tasks:
    - name: Copy base tf module dir to remotes
      copy:
        dest: ~/terraform/
        src: terraform/

    - name: Copy live tf module dir to remotes
      copy:
        dest: "~/live/{{ env }}/"
        src: "live/{{ env }}/"

    - name: Run Terraform Task
      check_mode: "{{ plan_only }}" # can pass via env yes | no
      register: terraform
      community.general.terraform:
        project_path: "~/live/{{ env }}/"
        state: "{{ state }}"
        variables: "{{ terraform_tvars | default(omit) }}"
        variables_files: "{{ terraform_tvars_files | default(omit) }}"
        backend_config_files: "{{ backend_config_files | default(omit) }}"
        force_init: true

    - name: View Output
      debug: var=terraform.stdout_lines
